### ISSUE TITLE
Overflow makes some nodes inaccessible

### ISSUE THREAD

**Issue by KristjanLaane** [strike-digital/node_pie#28]
i just noticed some of the nodes are not visible on the screen, so i cannot access them. 
The bottom of the Rotation category for instance:
![image](https://github.com/strike-digital/node_pie/assets/1708294/60c85eed-be33-4928-8345-b21c7889b03a)
And if have many custom node groups then they dont fit either and push the Vector category completely off the screen. 
There are many different kinds of solution to the problem, im just reporting the issue :)

**Comment by strike-digital** [comment]
Yeah I had this issue before, unfortunately there's not much you can do about it other than changing the addon preferences.

The way it works is that if the pie menu is smaller than the height of the window it will move it up to fit, but otherwise it will just cut it off. One way to help is in the preferences to change the groups to display as a submenu, rather than as a list. And if that doesn't work then you could also change the minimum node height so that it is even smaller.

**Comment by KristjanLaane** [comment]
thanks, your suggestions fix it enough to be workable.
