### ISSUE TITLE
Node Pie not compatible with AN, SV custom nodes

### ISSUE THREAD

**Issue by FredRus** [strike-digital/node_pie#9]
I tried to use the addon for Sverchok and animation nodes but did not work. I don't know why only sorcar worked fine but the other two didn't

**Comment by strike-digital** [comment]
Unfortunately, it seems that Animation nodes and Sverchok use a custom menu system, rather than the officially supported blender API for creating node add menus, which means that node pie can't find which nodes are available, and what categories to put them in...

I don't think there's any good way of fixing this unfortunately :(
